---
language: rust
dist: xenial
rust:
  # automaat-server currently requires nightly due to some of its dependencies.
  # this will be changed in the near future.
  # - stable
  # - beta
  - nightly
cache:
  directories:
    - $HOME/.cache/sccache
    - $HOME/.cargo
    - $HOME/.npm
    - $HOME/.rustup
env:
  global:
    - CARGO_BUILD_JOBS=8
    - CARGO_TERM_COLOR=always
    - RUSTC_WRAPPER=~/.cargo/bin/sccache
    - SCCACHE_ERROR_LOG=$HOME/sccache.log
    - SCCACHE_IDLE_TIMEOUT=0
    - SCCACHE_VERSION=0.2.8
matrix:
  # allow_failures:
  #   - rust: nightly
  fast_finish: true
install:
  # install sccache for improved build caching
  - env RUSTC_WRAPPER= cargo i sccache --version "$SCCACHE_VERSION" || true

  # configure rustup
  - echo "$TRAVIS_RUST_VERSION" > rust-toolchain
  - rustup component add rustfmt
  - rustup show

  # install nodejs + packages
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g prettier prettier-plugin-toml
before_script:
  - env RUST_LOG=sccache=error sccache --start-server
script:
  # lint :allthethings:
  - prettier --check "*.{graphql,toml,yml,yaml,md}" !Makefile.toml
  - prettier --check "./!(target)/**/*.{graphql,toml,yml,yaml,md}"
  - cargo fmt -- --check

  # tests
  - cargo build  --all --bins --examples --tests --benches --all-targets --all-features
  - cargo clippy --all --bins --examples --tests --benches --all-targets --all-features
  - cargo test   --all --bins --examples --tests --benches --all-targets --all-features
  - cargo doc    --all --bins --all-features --no-deps --document-private-items

  # stop sccache
  - sccache --stop-server || true
  - cat "$SCCACHE_ERROR_LOG"
services:
  - postgresql
  - redis-server
notifications:
  email: false
