---
language: rust
dist: xenial
rust:
  # automaat-server currently requires nightly due to its `rocket` dependency,
  # this will be changed in the near future.
  # - stable
  # - beta
  - nightly
cache: cargo
matrix:
  # allow_failures:
  #   - rust: nightly
  fast_finish: true
before_script:
  - echo "$TRAVIS_RUST_VERSION" > rust-toolchain
  - rustup component add rustfmt
  - rustup show
script:
  - cargo fmt -- --check
  - cargo doc --all --all-features --no-deps
  - cargo build --all --all-features
  - cargo test --all --all-features

  # web-client is not part of the top-level workspace
  - cd src/web-client
  - cargo fmt -- --check
  - cargo doc --all --all-features --no-deps
  - cargo build --all --all-features
  - cargo test --all --all-features
services:
  - redis-server
notifications:
  email: false
