[workspace]
members = [
    "src/core",
    "src/processors/git-clone",
    "src/processors/print-output",
    "src/processors/redis-command",
    "src/processors/shell-command",
    "src/processors/string-regex",
    "src/server",
]
