# cargo-release workflow:
#
# * cargo install cargo-release
# * cargo release <MAJOR|MINOR|PATCH> --manifest-path src/<crate>/Cargo.toml --dry-run
sign-commit = true
no-dev-version = true
tag-message = "{{crate_name}} v{{version}}"
pre-release-commit-message = "release: {{crate_name}} v{{version}}"
